// -*- coding: utf-8 -*-
// La lingua della casella.
//
// Schema: l'ITALIANO fa da chiave. Il codice resta scritto in italiano,
// leggibile com'era, e qui c'e' solo la traduzione. Due vantaggi che
// contano davvero: le chiavi non si inventano (sono la frase stessa), e
// una scritta non ancora tradotta resta in italiano invece di sparire o
// di mostrare un codice tipo "eti.mostra_icona".
//
// ATTENZIONE: le chiavi della CONFIGURAZIONE non si toccano mai - `icona`,
// `colore`, `posti`, `mostra_cursore` e compagnia stanno scritte dentro
// alle plance di chi usa la casella, e tradurle vorrebbe dire rompere ogni
// installazione esistente. Qui si traduce solo quello che si LEGGE.
//
// Questo file lo genera uno script dalle stringhe vere del codice: le
// chiavi non si scrivono a mano. Un apostrofo tipografico al posto di uno
// dritto e la traduzione non si aggancia piu', in silenzio.

let LINGUA = 'it';
// La lingua vera, per come si scrivono numeri e date: un tedesco legge le
// scritte in inglese ma i numeri li vuole coi suoi punti.
let LOCALE = 'it-IT';
let LOCALE_BUONA = null;

// Che lingua parla l'utente lo sa gia' Home Assistant: gliela chiedo.
// Tutto quello che non e' italiano prende l'inglese.
export function scegliLingua(hass) {
  const l = String((hass && ((hass.locale && hass.locale.language) || hass.language)) || '')
    .toLowerCase();
  // Se non lo so ancora NON decido: `setConfig` puo' arrivare prima di
  // `hass`, e mettere 'en' li' vorrebbe dire scrivere le linguette in
  // inglese a un utente italiano - si scrivono una volta sola, quindi
  // non si rimedia piu'.
  if (!l) return LINGUA;
  LOCALE = l;
  LOCALE_BUONA = null;
  LINGUA = l.indexOf('it') === 0 ? 'it' : 'en';
  return LINGUA;
}

export function laLingua() { return LINGUA; }

// Per toLocaleString: numeri e date nel formato di chi guarda. La sigla
// arriva da Home Assistant e potrebbe non piacere a Intl: la provo una
// volta sola, perche' un errore qui lascerebbe la casella bianca.
export function laLocale() {
  if (LOCALE_BUONA === null) {
    try {
      (0).toLocaleString(LOCALE);
      LOCALE_BUONA = LOCALE;
    } catch (e) {
      LOCALE_BUONA = LINGUA === 'it' ? 'it-IT' : 'en-GB';
    }
  }
  return LOCALE_BUONA;
}

// Se la scritta non c'e' nel dizionario torna com'era: meglio una frase in
// italiano che un buco.
export function T(testo) {
  if (LINGUA === 'it' || !testo) return testo;
  const t = EN[testo];
  return t === undefined ? testo : t;
}

// Le voci delle tendine passano dritte a ha-form dentro allo schema: le
// traduco qui, quando lo schema esce, invece di tenere la tabella delle
// sezioni in due lingue. La firma dello schema guarda i nomi, non le
// scritte, quindi tradurle non fa ricostruire niente.
export function traduciSchema(elenco) {
  if (LINGUA === 'it') return elenco;
  return (elenco || []).map((voce) => {
    if (voce && Array.isArray(voce.schema)) {
      // anche il titolo del cassetto: negli schemi delle schede dei consumi
      // le sezioni si chiamano `title`
      const dentro = { ...voce, schema: traduciSchema(voce.schema) };
      if (voce.title) dentro.title = T(voce.title);
      return dentro;
    }
    const opz = voce && voce.selector && voce.selector.select
      && voce.selector.select.options;
    if (!Array.isArray(opz)) return voce;
    return { ...voce,
      selector: { ...voce.selector,
        select: { ...voce.selector.select,
          options: opz.map((o) => (o && o.label ? { ...o, label: T(o.label) } : o)) } } };
  });
}

// Le scritte dentro a un pezzo di HTML scritto a mano (innerHTML): traduco
// quello che sta FRA i tag e non tocco i tag. Il testo che non e' nel
// dizionario resta com'e', come in T(). Serve una passata sola per blocco,
// e i blocchi si costruiscono una volta sola.
export function TH(html) {
  if (LINGUA === 'it' || !html) return html;
  return String(html)
    .replace(/>([^<>]+)</g, (tutto, dentro) => {
      const pulito = dentro.trim();
      if (!pulito) return tutto;
      const t = EN[pulito];
      return t === undefined ? tutto : '>' + dentro.replace(pulito, t) + '<';
    })
    // meta' della scocca sono `title=`: i tastini del lettore non hanno
    // scritte, solo il fumetto che dice cosa fanno.
    .replace(/(title|placeholder|aria-label)="([^"<>]+)"/g, (tutto, att, dentro) => {
      const t = EN[dentro.trim()];
      return t === undefined ? tutto : att + '="' + t + '"';
    })
    .replace(/(title|placeholder|aria-label)='([^'<>]+)'/g, (tutto, att, dentro) => {
      const t = EN[dentro.trim()];
      return t === undefined ? tutto : att + "='" + t + "'";
    });
}

export const EN = {
  "Si accende in base ad altre entita: basta che una sia attiva (es. i watt che escono invece della carica)": "On when another entity is active - any one of them is enough (e.g. the watts going out instead of the charge)",
  "Si accende solo quando l'entita' vale esattamente (es. 95)": "On only when the entity reads exactly this (e.g. 95)",
  "Sempre a colori (anche da spenta)": "Always in colour (even when off)",
  "Quando si muove (icona ed effetti)": "When it animates (icon and effects)",
  "Cosa fa quando la tocchi": "What happens when you tap it",
  "Riempi la casella con l'immagine della telecamera, viva": "Fill the tile with the live camera image",
  "Ogni quanti secondi si rifa l'immagine": "How often the image refreshes (seconds)",
  "Quali entita vogliono dire che STA CARICANDO (di solito non serve: basta chiamare carica una misura)": "Which entities mean IT IS CHARGING (usually not needed: a sensor named \"charge\" is enough)",
  "Elenco In coda (serve Music Assistant)": "Queue list (needs Music Assistant)",
  "Colore quando e accesa": "Colour when on",
  "Colore personalizzato (vale solo scegliendo \"personalizzato\" qui sopra)": "Custom colour (only applies if you pick \"custom\" above)",
  "Quale striscia mostrare": "Which strip to show",
  "Colore del nome e del sottotitolo (vuoto = quello del tema)": "Colour of the name and subtitle (empty = the theme's)",
  "Colore del valore, quello grande (vuoto = come il nome)": "Colour of the big value (empty = same as the name)",
  "Comandi della musica dentro la casella": "Music controls inside the tile",
  "Tasti rapidi (tapparelle, serrature, aspirapolvere)": "Quick buttons (shutters, locks, vacuum)",
  "Striscia del colore dentro la casella": "Colour strip inside the tile",
  "La barra arriva a (es. 800, invece dei 1200 dell'entita)": "Slider tops out at (e.g. 800 instead of the entity's 1200)",
  "La barra parte da (lascia vuoto = minimo dell'entita)": "Slider starts at (empty = the entity's minimum)",
  "Come e disposta la casella": "How the tile is laid out",
  "Sensore del percorso (Waze, Google): se c'e, usa i km su strada": "Route sensor (Waze, Google): if set, uses road distance",
  "Effetto della casella": "Tile effect",
  "Entita (lasciala vuota se la casella serve solo ad aprire il pop-up)": "Entity (leave it empty if the tile only opens the pop-up)",
  "Come si apre la finestra": "How the window opens",
  "Quanto dura l'apertura (millesimi di secondo)": "How long the opening takes (milliseconds)",
  "Foto di sfondo del pop-up - indirizzo, es. /local/foto.jpg": "Pop-up background photo - address, e.g. /local/photo.jpg",
  "Larghezza del pop-up in punti (vuoto = 560, come tutti gli altri)": "Pop-up width in pixels (empty = 560, like everyone else)",
  "Tinta della finestra del pop-up (le schede dentro hanno la loro, qui sotto)": "Pop-up window tint (the cards inside have their own, below)",
  "Titolo del pop-up": "Pop-up title",
  "Trasparenza del pop-up (%)": "Pop-up transparency (%)",
  "Fai girare la copertina tonda come un disco": "Spin the round album art like a record",
  "Mostra il grafico dell'andamento dentro la casella": "Show the history chart inside the tile",
  "Colore del grafico (vuoto = come la casella)": "Chart colour (empty = same as the tile)",
  "Quante ore di storia (di serie 24)": "How many hours of history (24 by default)",
  "Come si disegna": "How it is drawn",
  "Casella grande": "Big tile",
  "Icona animata": "Animated icon",
  "Usa l'icona che l'entita ha gia in Home Assistant, se ce l'ha": "Use the icon the entity already has in Home Assistant, if any",
  "Icona di Home Assistant (cercala qui; vince su quella sotto)": "Home Assistant icon (search here; beats the one below)",
  "Immagine al posto dell'icona": "Image instead of the icon",
  "Immagine di quando e acceso (anche una gif)": "Image for when it is on (a GIF works too)",
  "L'icona in grande dietro alle scritte": "The big faded icon behind the text",
  "Quanto si vede l'icona dietro (%)": "How visible the icon behind is (%)",
  "Trasparenza dell'icona o della foto (%)": "Icon or photo transparency (%)",
  "Indirizzo web da aprire (per l'azione \"Apri un indirizzo web\")": "Web address to open (for the \"Open a web address\" action)",
  "Misure mostrate in basso (aggiungine altre da qui)": "Readings shown at the bottom (add more here)",
  "Scrivi un nome anche sulle misure che non hai chiamato tu": "Also label the readings you have not named yourself",
  "Intensita del colore (%)": "Colour strength (%)",
  "Casse tra cui scegliere (i tastini in alto nella casella)": "Speakers to choose from (the small buttons at the top)",
  "Meteo nell'angolo (scegli l'entita del meteo)": "Weather in the corner (pick the weather entity)",
  "Quanto si vede la scena meteo (%) - 0 lascia solo il colore": "How visible the weather scene is (%) - 0 leaves only the colour",
  "Barra dentro la casella (luci, ventole, musica, valori da impostare)": "Slider inside the tile (lights, fans, music, values to set)",
  "Scrivi da quanto tempo e in questo stato": "Show how long it has been in this state",
  "Quanti chilometri da casa, in linea d'aria (persone)": "Distance from home as the crow flies (people)",
  "Mostra l'icona (toglila per lasciare solo le scritte)": "Show the icon (turn it off to leave only the text)",
  "Tasto Casse: unisci gli altoparlanti e regola i volumi": "Speakers button: group the speakers and set the volumes",
  "Nome mostrato": "Display name",
  "Nascondi il numerino in fondo alla barra": "Hide the little number at the end of the slider",
  "Nascondi il valore": "Hide the value",
  "Sfondo del riquadro casse e sorgenti (vuoto = scuro di serie; le scritte seguono il colore della scritta)": "Background of the speakers and sources panel (empty = the usual dark; the text follows the text colour)",
  "Trasparenza del riquadro casse e sorgenti (%)": "Transparency of the speakers and sources panel (%)",
  "Pop-up bubble-card da aprire (es. #luci)": "bubble-card pop-up to open (e.g. #lights)",
  "Trasparenza dei riquadri ricerca, sfoglia e coda (%)": "Transparency of the search, browse and queue panels (%)",
  "Quali entita vogliono dire che STA DANDO CORRENTE (di solito non serve: basta chiamare scarica una misura)": "Which entities mean IT IS SUPPLYING POWER (usually not needed: a sensor named \"discharge\" is enough)",
  "Passa da sola alla cassa che sta suonando": "Follow whichever speaker is playing",
  "Servizio da chiamare (es. number.set_value)": "Service to call (e.g. number.set_value)",
  "Dati del servizio, in YAML (es. value: 95)": "Service data, in YAML (e.g. value: 95)",
  "Come si adatta la foto": "How the photo fits",
  "Sfondo della casella (tinta)": "Tile background (tint)",
  "Copertina del disco come sfondo": "Album art as background",
  "Foto di sfondo - indirizzo, es. /local/foto.jpg": "Background photo - address, e.g. /local/photo.jpg",
  "Usa il meteo come sfondo di tutta la casella": "Use the weather as the background of the whole tile",
  "Quanto sfocarla (0 = nitida)": "How much to blur it (0 = sharp)",
  "Velo scuro sulla foto o sulla copertina (%) - serve a leggere il testo": "Dark veil over the photo or album art (%) - so the text stays readable",
  "Soglia di accensione (W)": "On threshold (W)",
  "Tasto Sorgente: scegli l'ingresso del lettore": "Source button: pick the player's input",
  "Sottotitolo scritto da te (facoltativo)": "Subtitle you write yourself (optional)",
  "Sottotitolo preso da un'altra entita (es. l'indirizzo)": "Subtitle taken from another entity (e.g. the address)",
  "Tempo del brano e barra di avanzamento": "Track time and progress bar",
  "Cosa fa quando la tieni premuta": "What happens when you hold it down",
  "Trasparenza della casella (%)": "Tile transparency (%)",
  "Usa la foto dell'entita, se ce l'ha (persone, copertine)": "Use the entity's own picture, if it has one (people, album art)",
  "Velocita dell'effetto (%) - 100 e normale": "Effect speed (%) - 100 is normal",
  "Tastini cerca / sfoglia / coda / schermo intero": "Small buttons: search / browse / queue / fullscreen",
  "Cuoricino dei preferiti": "Favourite heart",
  "Auto": "Auto",
  "In carica": "Charging",
  "Pulisce": "Cleaning",
  "Chiusa": "Closed",
  "Raffredda": "Cooling",
  "In scarica": "Discharging",
  "Scollegato": "Disconnected",
  "Alla base": "Docked",
  "Errore": "Error",
  "Carica": "Full",
  "Riscalda": "Heating",
  "In casa": "Home",
  "Fermo": "Idle",
  "Ferma": "Not charging",
  "Fuori casa": "Away",
  "Spento": "Off",
  "Acceso": "On",
  "Aperta": "Open",
  "In pausa": "Paused",
  "In riproduzione": "Playing",
  "Registra": "Recording",
  "Rientra": "Returning",
  "In attesa": "Standby",
  "In diretta": "Streaming",
  "Assente": "Unavailable",
  "Via cavo": "Wired",
  "Base": "Basics",
  "Cosa c'e scritto": "What it says",
  "Quando la casella e accesa": "When the tile counts as on",
  "Icona": "Icon",
  "Batteria: carica e scarica": "Battery: charging and discharging",
  "Aspetto": "Looks",
  "Come e fatta": "Shape",
  "Colore della scritta": "Text colour",
  "Effetti": "Effects",
  "Sfondo": "Background",
  "Tinta della casella": "Tile tint",
  "La telecamera in diretta": "Live camera",
  "Foto di sfondo": "Background photo",
  "La copertina del brano come sfondo": "Album art as background",
  "Il cielo del meteo": "Weather sky",
  "Comandi": "Controls",
  "Barra dentro la casella": "Slider inside the tile",
  "Tasti rapidi": "Quick buttons",
  "Striscia del colore (luci)": "Colour strip (lights)",
  "Grafico": "Chart",
  "Musica": "Music",
  "Comandi del lettore": "Player controls",
  "Casse e sorgenti": "Speakers and sources",
  "Il riquadro delle casse": "The speakers panel",
  "Persone": "People",
  "Dove si trova": "Where they are",
  "Tocco": "Tap",
  "Pop-up": "Pop-up",
  "Come si apre": "How it opens",
  "Quanto e largo il pop-up": "Pop-up width",
  "Come e vestito il pop-up": "Pop-up looks",
  "Pezzi": "Pieces",
  "finestra": "window",
  "Classica - icona in basso, valore a destra": "Classic - icon bottom left, value right",
  "Persona - foto a sinistra, stato e via accanto": "Person - photo left, state beside it",
  "Musica - copertina tonda grande e onda del tempo": "Music - big round album art and a waveform",
  "Musica - come la tua ytmusic-card": "Music - like the ytmusic-card",
  "Alone - morbido": "Glow - soft",
  "Alone - che respira": "Glow - breathing",
  "Alone - diffuso e grande": "Glow - wide and soft",
  "Alone - doppio bordo": "Glow - double border",
  "Luce - neon dentro e fuori": "Light - neon inside and out",
  "Luce - che gira sul bordo": "Light - running around the border",
  "Luce - riflesso che scorre": "Light - sweeping reflection",
  "Luce - spia lampeggiante": "Light - blinking indicator",
  "Luce - lampeggio (per gli avvisi)": "Light - flashing (for alerts)",
  "Superficie - vetro smerigliato": "Surface - frosted glass",
  "Superficie - sfondo tinto": "Surface - tinted background",
  "Superficie - sfondo che si muove": "Surface - moving background",
  "Superficie - incavo": "Surface - inset",
  "Movimento - onda che sale": "Motion - rising wave",
  "Movimento - battito": "Motion - heartbeat",
  "Movimento - icona che fluttua": "Motion - floating icon",
  "Movimento - icona che pulsa": "Motion - pulsing icon",
  "Al passaggio - si ingrandisce": "On hover - grows",
  "Al passaggio - si inclina": "On hover - tilts",
  "Nessun effetto": "No effect",
  "Si muove solo quando e attiva": "Only while the entity is active",
  "Si muove sempre": "Always",
  "Non si muove mai": "Never",
  "Riempie la casella (taglia i bordi)": "Fills the tile (crops the edges)",
  "Tutta intera dentro la casella": "The whole photo inside the tile",
  "Grandezza vera della foto": "Actual photo size",
  "Solo la tinta (arcobaleno)": "Colour only (rainbow)",
  "Solo il bianco caldo/freddo": "Warm/cool white only",
  "Tutte e due le strisce": "Both strips",
  "Area piena": "Filled area",
  "Solo la linea": "Line only",
  "Accendi / spegni": "Toggle",
  "Esegui un servizio (es. imposta un valore)": "Call a service (e.g. set a value)",
  "Apri i dettagli": "Open more-info",
  "Apri un pop-up mio": "Open my own pop-up",
  "Apri la scheda elettrodomestico (si prepara da sola)": "Open the appliance card (sets itself up)",
  "Apri la scheda energia della casa (si prepara da sola)": "Open the home energy card (sets itself up)",
  "Apri Google Maps sulla posizione": "Open Google Maps at the location",
  "Apri un indirizzo web": "Open a web address",
  "Apri un pop-up bubble-card (#nome)": "Open a bubble-card pop-up (#name)",
  "Niente": "Nothing",
  "Sale e sfuma - discreta": "Rises and fades - discreet",
  "Sboccia dalla casella che hai toccato": "Blooms from the tile you tapped",
  "Entra dal basso, come un cassetto": "Slides up from the bottom, like a drawer",
  "Nessuna animazione": "No animation",
  "Tieni premuto e trascina per allargare o stringere": "Press and drag to make it wider or narrower",
  "Tieni premuto e trascina per alzare o abbassare": "Press and drag to make it taller or shorter",
  "Volume del gruppo": "Group volume",
  "Abbassa di 1": "Down by 1",
  "Alza di 1": "Up by 1",
  "Riattiva l'audio": "Unmute",
  "Silenzia": "Mute",
  "Alza e abbassa tutte insieme, ognuna dal suo volume": "Raises and lowers them together, each from its own volume",
  "Tutte le casse": "All the speakers",
  "Volume di tutte le casse del gruppo": "Volume of every speaker in the group",
  "pausa": "pause",
  "acqua": "water",
  "aereo": "plane",
  "aggiornamento": "update",
  "albero": "tree",
  "allarme": "alarm",
  "altoparlante": "speaker",
  "ascensore": "lift",
  "asciugatrice": "tumble dryer",
  "aspirapolvere": "vacuum",
  "assistente": "assistant",
  "attenzione": "warning",
  "attrezzi": "tools",
  "autobus": "bus",
  "automobile": "car",
  "bagno": "bathroom",
  "bambino": "child",
  "batteria": "battery",
  "battito": "heartbeat",
  "benzina": "petrol",
  "bici": "bike",
  "bilancia": "scales",
  "birra": "beer",
  "bollitore": "kettle",
  "bombola": "gas bottle",
  "bussola": "compass",
  "cacciavite": "screwdriver",
  "caffe": "coffee",
  "caldaia": "boiler",
  "calendario": "calendar",
  "campana": "bell",
  "campanello": "doorbell",
  "campanello_video": "video doorbell",
  "cancello": "gate",
  "candela": "candle",
  "cane": "dog",
  "carrello": "trolley",
  "casa": "house",
  "casa_corrente": "house power",
  "cassetta_posta": "letterbox",
  "chiamata": "call",
  "chiave": "key",
  "chiave_inglese": "spanner",
  "ciabatta": "power strip",
  "condizionatore": "air conditioner",
  "contatore": "meter",
  "contatore_luce": "electricity meter",
  "corrente_ac": "AC power",
  "corrente_dc": "DC power",
  "corriere": "courier",
  "corsa": "running",
  "cucina": "kitchen",
  "cuffie": "headphones",
  "cuore": "heart",
  "deumidificatore": "dehumidifier",
  "divano": "sofa",
  "erba": "grass",
  "faretti": "spotlights",
  "filtro_aria": "air filter",
  "finestra_aperta": "open window",
  "fiore": "flower",
  "fornello": "hob",
  "forno": "oven",
  "frigo": "fridge",
  "frigorifero": "fridge",
  "fulmine": "lightning",
  "fumo": "smoke",
  "fuoco": "fire",
  "gatto": "cat",
  "gioco": "game",
  "goccia": "drop",
  "gruppo": "group",
  "ingranaggio": "cog",
  "interruttore": "switch",
  "irrigazione": "irrigation",
  "lampadina_accesa": "bulb on",
  "lampione": "street lamp",
  "lavastoviglie": "dishwasher",
  "lavatrice": "washing machine",
  "lavatrice_mdi": "washing machine (mdi)",
  "lavoro": "work",
  "led": "LED",
  "letto": "bed",
  "libro": "book",
  "lucchetto": "padlock",
  "lucchetto_aperto": "open padlock",
  "luce": "light",
  "luna": "moon",
  "macchina_caffe": "coffee machine",
  "manopola": "knob",
  "mappa": "map",
  "martello": "hammer",
  "medicina": "medicine",
  "mela": "apple",
  "messaggio": "message",
  "microfono": "microphone",
  "microonde": "microwave",
  "misura": "gauge",
  "moto": "motorbike",
  "movimento": "motion",
  "musica": "music",
  "nebbia": "fog",
  "neve": "snow",
  "notifica": "notification",
  "nuvola": "cloud",
  "nuvola_cloud": "cloud",
  "occhio": "eye",
  "ombrello": "umbrella",
  "orologio": "clock",
  "orologio_polso": "watch",
  "pacco": "parcel",
  "palestra": "gym",
  "pannello_solare": "solar panel",
  "parcheggio": "parking",
  "pc_fisso": "desktop PC",
  "persona": "person",
  "pesce": "fish",
  "pianta": "plant",
  "pioggia": "rain",
  "piscina": "pool",
  "pompa": "pump",
  "porta": "door",
  "porta_scorrevole": "sliding door",
  "portatile": "laptop",
  "posizione": "location",
  "powerstation": "power station",
  "presa": "socket",
  "purificatore": "air purifier",
  "radiatore": "radiator",
  "regolatore": "dimmer",
  "ricarica_auto": "car charger",
  "riciclo": "recycling",
  "robot_aspirapolvere": "robot vacuum",
  "robot_mdi": "robot (mdi)",
  "scale": "stairs",
  "scena": "scene",
  "scopa": "broom",
  "scrivania": "desk",
  "scudo": "shield",
  "scuola": "school",
  "sensore_movimento": "motion sensor",
  "serranda": "shutter",
  "serratura": "lock",
  "sirena": "siren",
  "sole": "sun",
  "sole_nuvole": "sun and clouds",
  "sonno": "sleep",
  "spazzatura": "rubbish",
  "spina": "plug",
  "stampante": "printer",
  "stampante3d": "3D printer",
  "stampante_3d": "3D printer (mdi)",
  "stanza": "room",
  "stella": "star",
  "striscia_led": "LED strip",
  "sveglia": "alarm clock",
  "tachimetro": "speedometer",
  "tapparella": "roller blind",
  "telecamera": "camera",
  "telecomando": "remote",
  "telefono": "phone",
  "televisore": "TV",
  "temporale": "storm",
  "tende": "curtains",
  "termometro": "thermometer",
  "termosifone": "radiator",
  "termostato": "thermostat",
  "tosaerba": "lawn mower",
  "tostapane": "toaster",
  "traliccio": "pylon",
  "trasferisci": "transfer",
  "treno": "train",
  "tv_mdi": "TV (mdi)",
  "umidificatore": "humidifier",
  "valigia": "suitcase",
  "ventilatore": "fan",
  "vento": "wind",
  "ventola": "fan",
  "vino": "wine",
  "wc": "toilet",
  "wifi_mdi": "wifi (mdi)",
  "Immagine di quando e' acceso (anche una gif)": "Image for when it is on (a GIF works too)",
  "Pausa": "Pause",
  "Premi il pulsante: si apre la galleria del telefono o le cartelle del PC. In alternativa scrivi l'indirizzo nel campo qui sopra (es. /local/foto.jpg).": "Press the button: your phone gallery or your PC folders open. Or type the address in the field above (e.g. /local/photo.jpg).",
  "Riproduci": "Play",
  "Scegli un'altra foto": "Pick another photo",
  "Scegli una foto dal telefono o dal PC": "Pick a photo from your phone or PC",
  "Usa un'immagine mia (telefono o PC)": "Use a picture of mine (phone or PC)",
  "si vede solo mentre lavora: alla base torna quella di sopra": "it shows only while it is working: back on the dock the one above returns",
  "\" non funziona con questa entita.": "\" does not work with this entity.",
  "Album": "Albums",
  "Apri": "Open",
  "Apri la serratura": "Unlock",
  "Artisti": "Artists",
  "Brani": "Tracks",
  "Brani, album, artisti...": "Tracks, albums, artists...",
  "Che ne faccio": "What do I do with it",
  "Chiudi": "Close",
  "Chiudi a chiave": "Lock",
  "Consigliati": "Recommended",
  "Distanza in linea d’aria dal punto che Home Assistant considera casa: su strada e sempre di piu": "Straight-line distance from the point Home Assistant calls home: by road it is always more",
  "Eccezionale": "Exceptional",
  "Grandine": "Hail",
  "La scheda \"": "The card \"",
  "Libreria": "Library",
  "Mostra la coda": "Show the queue",
  "Nebbia": "Fog",
  "Neve": "Snow",
  "Nevischio": "Sleet",
  "Nuvoloso": "Cloudy",
  "Parz. nuvoloso": "Partly cloudy",
  "Pioggia": "Rain",
  "Pioggia forte": "Heavy rain",
  "Play / pausa": "Play / pause",
  "Playlist": "Playlists",
  "Porta qui la coda che sta suonando": "Bring the playing queue here",
  "Precedente": "Previous",
  "Preferito": "Favourite",
  "Radio": "Radio",
  "Recenti": "Recent",
  "Schermo intero": "Full screen",
  "Sereno": "Clear",
  "Sfoglia la musica": "Browse the music",
  "Successivo": "Next",
  "Temporale": "Storm",
  "Torna alla base": "Back to the dock",
  "Tutto": "Everything",
  "Vento": "Windy",
  "Ventoso": "Windy",
  "da poco": "just now",
  "da un giorno": "for a day",
  "da {n} giorni": "for {n} days",
  "da {n} h": "for {n} h",
  "da {n} h {m}": "for {n} h {m}",
  "da {n} min": "for {n} min",
  "Aggiungi tutte le schede che vuoi: sono le stesse di Home Assistant, e le puoi modificare quando vuoi. Per riordinarle tieni premuto il puntino a sinistra e trascinale.": "Add as many cards as you like: they are the Home Assistant ones, and you can change them whenever you want. To reorder them hold the dot on the left and drag.",
  "Automatica": "Automatic",
  "Casse": "Speakers",
  "Casse del gruppo": "Speakers in the group",
  "Cerca": "Search",
  "Cerca l'icona: luce, presa, porta, auto...": "Search the icon: light, plug, door, car...",
  "Contenuto del pop-up": "Pop-up contents",
  "Dove va ogni pezzo": "Where each piece goes",
  "In coda": "Queue",
  "La ricerca ha bisogno di Music Assistant: qui non lo trovo.": "Search needs Music Assistant: I cannot find it here.",
  "La ricerca non ha risposto (": "The search did not answer (",
  "Non c'e' niente in coda": "The queue is empty",
  "Non ho trovato niente.": "I found nothing.",
  "Non riesco a leggere la coda": "I cannot read the queue",
  "Non risponde (": "No answer (",
  "Per il meteo non serve sceglierla: l'icona la decide il tempo che fa (sole, nuvole, pioggia, neve, temporale, nebbia, vento) e cambia da sola.": "For weather you do not need to pick one: the icon follows the sky (sun, clouds, rain, snow, storm, fog, wind) and changes by itself.",
  "Prendi il nome, il valore, l'icona o una misura e trascinali dove vuoi dentro alla casella qui sotto. Tocca un pezzo e sul suo angolo compare un quadratino giallo: tienilo premuto e trascina per ingrandirlo o rimpicciolirlo.": "Pick up the name, the value, the icon or a reading and drag them wherever you like inside the tile below. Tap a piece and a little yellow square appears on its corner: hold it and drag to make it bigger or smaller.",
  "Qui non c'e niente.": "Nothing here.",
  "Schede dentro il pop-up": "Cards inside the pop-up",
  "Sensori collegati a questa entita": "Sensors related to this entity",
  "Sorgente": "Source",
  "Sto cercando...": "Searching...",
  "Tocca la ruota per scegliere il colore che vuoi: e' quello dell'alone, del bordo e di tutti gli effetti.": "Tap the wheel to pick the colour you want: it is the one of the glow, the border and every effect.",
  "Un attimo...": "One moment...",
  "errore": "error",
  " - tocca per aprire Google Maps": " - tap to open Google Maps",
  " - tocca per i dettagli": " - tap for the details",
  "Stai sistemando: questa casella. Per una scheda del pop-up, toccala nell'anteprima qui di fianco.": "You are arranging: this tile. For a card in the pop-up, tap it in the preview beside.",
  "Il nome compare accanto al numero. Lascia vuoto per non scrivere niente.": "The name shows next to the number. Leave it empty to show nothing.",
  "Le impostazioni di questa scheda non si sono caricate. Il codice lo trovi qui sotto.": "The settings for this card did not load. You will find the code below.",
  "Mette negli appunti solo la disposizione e la grandezza: incollale nel codice di un'altra casella e premi Applica": "Copies only the layout and the size: paste them into the code of another tile and press Apply",
  "disposizione messa da parte: vai sull'altra casella e premi \"Incolla la disposizione\"": "layout copied: go to the other tile and press \"Paste the layout\"",
  "Versione della card: se non e' quella che ti aspetti, il browser sta ancora usando una copia vecchia (ricarica con Ctrl+F5)": "Card version: if it is not the one you expect, the browser is still using an old copy (reload with Ctrl+F5)",
  "Ancora nessuna scheda: il pop-up mostrera l'elenco dell'entita. Premi qui sotto per sceglierne una.": "No cards yet: the pop-up will show the entity list. Press below to pick one.",
  "Sto caricando ": "Uploading ",
  "Codice non valido: ": "Invalid code: ",
  "Pezzo: ": "Piece: ",
  "Incolla la disposizione di \"": "Paste the layout of \"",
  "+ Aggiungi scheda": "+ Add a card",
  "Aggiungi": "Add",
  "Altezza in punti": "Height in pixels",
  "Ancora nessuna scheda: il pop-up mostrera l'elenco dell'entita. Premi qui sotto per aggiungerne una.": "No cards yet: the pop-up will show the entity list. Press below to add one.",
  "Annulla": "Cancel",
  "Applica il codice": "Apply the code",
  "Carico le impostazioni della scheda...": "Loading the card settings...",
  "Cerca un'impostazione: meteo, colore, km...": "Search a setting: weather, colour, km...",
  "Codice della scheda (YAML)": "Card code (YAML)",
  "Codice di questa casella (YAML)": "Code of this tile (YAML)",
  "Codice non valido:": "Invalid code:",
  "Colore di questa misura": "Colour of this reading",
  "Come la lampada (colore vero della luce)": "Like the lamp (the light real colour)",
  "Come si chiamano le misure": "What the readings are called",
  "Copia la disposizione": "Copy the layout",
  "Grandezza": "Size",
  "Grandezza del pezzo in percentuale": "Piece size, as a percentage",
  "Grandezza vera": "Actual size",
  "Guarda come si apre": "See how it opens",
  "Il nome compare accanto al numero. Lascia vuoto per usare quello di Home Assistant.": "The name shows next to the number. Leave empty to use the Home Assistant one.",
  "Incolla la disposizione di “": "Paste the layout of “",
  "La sceglie la card guardando l'entita": "The card picks it by looking at the entity",
  "Larghezza in punti": "Width in pixels",
  "Le impostazioni di questa scheda non si sono aperte. Usa il codice qui sotto.": "This card settings did not open. Use the code below.",
  "Mette negli appunti solo la disposizione e la grandezza: il valore e l'entita restano quelli della casella dove la incolli": "Copies only the layout and the size: the value and the entity stay those of the tile you paste it into",
  "Nessuna impostazione con «": "No setting with «",
  "Non ho trovato sensori collegati. Puoi comunque aggiungerne a mano qui sopra.": "I found no related sensors. You can still add some by hand above.",
  "Non riesco a creare il contenuto della finestra.": "I cannot build the contents of the window.",
  "Non sono riuscito a caricarla (": "I could not upload it (",
  "Pezzo": "Piece",
  "Pezzo:": "Piece:",
  "Prendi la disposizione da": "Take the layout from",
  "Quanto e trasparente": "How transparent it is",
  "Quanto e' distante dal bordo di sopra, in percentuale": "Distance from the top edge, as a percentage",
  "Quanto e' distante dal bordo sinistro, in percentuale": "Distance from the left edge, as a percentage",
  "Rimetti come prima": "Put it back",
  "Rimetti tutto a posto": "Reset everything",
  "Scegli il colore": "Pick the colour",
  "Scegli prima un'entita nella scheda Base.": "Pick an entity in the Basics tab first.",
  "Segue la temperatura (freddo azzurro, caldo rosso)": "Follows the temperature (cold blue, warm red)",
  "Sfondo di questa scheda": "Background of this card",
  "Spunta quelli che vuoi vedere in basso nella casella.": "Tick the ones you want to see at the bottom of the tile.",
  "Stai sistemando:": "You are arranging:",
  "Stai sistemando: questa casella.": "You are arranging: this tile.",
  "Sto caricando": "Uploading",
  "Svuota la coda": "Clear the queue",
  "Tieni premuto e trascina per cambiare la grandezza della casella": "Press and drag to change the size of the tile",
  "Tieni premuto e trascina per cambiare la misura di questa scheda": "Press and drag to change the size of this card",
  "Tieni premuto e trascina per ingrandire o rimpicciolire": "Press and drag to make it bigger or smaller",
  "Tieni premuto e trascina per riordinare": "Press and drag to reorder",
  "Tocca per le previsioni": "Tap for the forecast",
  "Tocca per scegliere un'altra foto": "Tap to pick another photo",
  "Togli il colore": "Remove the colour",
  "Togli l'immagine": "Remove the image",
  "Togli la foto": "Remove the photo",
  "Torna al colore della casella": "Back to the tile colour",
  "Torna alla casella": "Back to the tile",
  "Un colore qualsiasi": "Any colour",
  "Versione della card: se non e' quella che ti aspetti, la pagina sta ancora usando una copia vecchia (ricarica con Ctrl+Shift+R)": "Card version: if it is not the one you expect, the page is still using an old copy (reload with Ctrl+Shift+R)",
  "da sinistra": "from the left",
  "disposizione messa da parte: vai sull'altra casella e premi Incolla": "layout copied: go to the other tile and press Paste",
  "oppure l'indirizzo: /local/mia.gif": "or the address: /local/mine.gif",
  "pronto: tocca un pezzo qui sopra": "ready: tap a piece above",
  "si apre qui di fianco - chiudila con la X o con Esc": "it opens right here - close it with the X or with Esc",
  "Piu' prese (ciabatte): una fila di tastini col loro nome": "Several sockets (power strips): a row of small buttons with their names",
  "Nome della scheda": "Card name",
  "Disegno": "Artwork",
  "Presa che misura (W) - o un altro numero da mostrare nella barra": "Socket that measures (W) - or any other number to show in the bar",
  "Sopra questi W e' «in funzione»": "Above these watts it is «running»",
  "Sopra questi W e' «in standby»": "Above these watts it is «standby»",
  "Fondo scala della barra": "Bar full scale",
  "Nome della barra (vuoto = Potenza attuale)": "Bar name (empty = Current power)",
  "Unita' della barra (vuoto = W)": "Bar unit (empty = W)",
  "Stato vero dell'apparecchio (facoltativo: integrazioni LG, Bosch...)": "The appliance's real state (optional: LG, Bosch integrations...)",
  "Tasto ⏻ nella barra in alto: cosa accende e spegne": "⏻ button in the top bar: what it switches on and off",
  "Secondo tasto per le prese USB (se ci sono)": "Second button for the USB sockets (if there are any)",
  "kWh di OGGI: il contatore di utenza a ciclo giornaliero": "TODAY's kWh: the utility meter on a daily cycle",
  "Euro di oggi: quei kWh per il prezzo": "Today's cost: those kWh times the price",
  "kWh del MESE: lo stesso contatore a ciclo mensile": "This MONTH's kWh: the same meter on a monthly cycle",
  "Euro del mese": "This month's cost",
  "Barre in piu' (una per ogni cosa che vuoi vedere in W)": "Extra bars (one for each thing you want to see in W)",
  "Sensore dell'ultimo ciclo (es. sensor.lavatrice_ciclo)": "Last-cycle sensor (e.g. sensor.washer_cycle)",
  "Seconda barra: un numero da 0 a 100 (avanzamento, umidita'...)": "Second bar: a number from 0 to 100 (progress, humidity...)",
  "Nome della seconda barra (vuoto = Avanzamento programma)": "Second bar name (empty = Programme progress)",
  "Ciclo in corso: energia gia' consumata (Wh o kWh)": "Cycle running: energy used so far (Wh or kWh)",
  "Ciclo in corso: minuti gia' fatti": "Cycle running: minutes done so far",
  "Ciclo in corso: minuti che mancano (per l'ora di fine)": "Cycle running: minutes left (for the finish time)",
  "Ciclo in corso: programma scelto": "Cycle running: programme chosen",
  "Ciclo in corso: fase (asciugatura, risciacquo...)": "Cycle running: phase (drying, rinsing...)",
  "Pagina delle notifiche (facoltativa)": "Notifications page (optional)",
  "Tinta della finestra del pop-up": "Colour of the pop-up window",
  "Trasparenza della finestra": "Window transparency",
  "Colore delle scritte nella finestra": "Colour of the text in the window",
  "Quanto scurisce quello che c'e' dietro": "How much it darkens what is behind",
  "Quanto sfoca quello che c'e' dietro": "How much it blurs what is behind",
  "Potenza della casa (W) - obbligatoria": "The house's power (W) - required",
  "Contatore dei kWh di OGGI (aiutante «contatore di utenza», ciclo giornaliero)": "TODAY's kWh meter («utility meter» helper, daily cycle)",
  "Sensore degli EURO di oggi (i kWh per il prezzo)": "Today's COST sensor (those kWh times the price)",
  "Contatore dei kWh del MESE (stesso aiutante, ciclo mensile)": "This MONTH's kWh meter (same helper, monthly cycle)",
  "Sensore degli EURO del mese": "This month's COST sensor",
  "Entità con la soglia d'allarme (facoltativa)": "Entity holding the alarm threshold (optional)",
  "Interruttori da mettere nelle impostazioni": "Switches to put in the settings",
  "Fondo scala della barra (W, es. 3300 con 3 kW)": "Bar full scale (W, e.g. 3300 on a 3 kW supply)",
  "Circuiti da mostrare con la barra (prese o sensori in W)": "Circuits to show with a bar (sockets or sensors in W)",
  "Top consumo automatico (cerca da solo tutte le prese che misurano)": "Automatic top consumer (finds every measuring socket by itself)",
  "Sotto questi W non e' «top»": "Below these watts it does not count as «top»",
  "Nome della voce «Non misurato»": "Name of the «Unmeasured» entry",
  "Prese da contare sempre (anche se escluse qui sotto)": "Sockets to always count (even if excluded below)",
  "Parole che fanno escludere un sensore (batterie, inverter...)": "Words that make a sensor excluded (batteries, inverters...)",
  "Conto di oggi voce per voce (es. sensor.costi_luce_oggi)": "Today's itemised bill (e.g. sensor.power_costs_today)",
  "Conto del mese voce per voce (es. sensor.costi_luce_mese)": "This month's itemised bill (e.g. sensor.power_costs_month)",
  "Contatore dei kWh del periodo della bolletta (bimestre)": "kWh meter for the billing period (two months)",
  "Contatore degli euro dello stesso periodo": "Cost meter for the same period",
  "Pagina delle notifiche (facoltativa, es. /lovelace/notifiche)": "Notifications page (optional, e.g. /lovelace/notifications)",
  "Vuoto = valgono le parole di serie (batterie, inverter, fotovoltaico, solar, grid...): ": "Empty = the built-in words apply (batteries, inverters, photovoltaic, solar, grid...): ",
  "Vuoto = nessuna forzatura. Serve solo per una presa che una parola qui sopra escluderebbe.": "Empty = nothing forced. Only needed for a socket that one of the words above would exclude.",
  "Vuoto = 5 W. Sotto questa soglia un apparecchio non vale come 'top'.": "Empty = 5 W. Below this an appliance does not count as 'top'.",
  "Vuoto = «Non misurato»: quanto consuma la casa fuori dalle prese che misurano.": "Empty = «Unmeasured»: what the house uses outside the sockets that measure.",
  "Quando e' acceso (soglie e barra)": "When it is on (thresholds and bar)",
  "Tasti di accensione": "Power buttons",
  "Sensore dell'ultimo ciclo": "Last-cycle sensor",
  "Ciclo in corso (mentre lavora)": "Cycle running (while it works)",
  "Seconda barra": "Second bar",
  "Aspetto e finestra del pop-up": "Look and pop-up window",
  "Tasti e interruttori": "Buttons and switches",
  "Barre dei circuiti": "Circuit bars",
  "Top consumo (chi consuma di piu')": "Top consumer (who uses the most)",
  "Lavatrice": "Washing machine",
  "Lavastoviglie": "Dishwasher",
  "Asciugatrice": "Tumble dryer",
  "Forno": "Oven",
  "Microonde": "Microwave",
  "Frigorifero": "Fridge",
  "Deumidificatore": "Dehumidifier",
  "Condizionatore": "Air conditioner",
  "Ventilatore": "Fan",
  "Boiler / scaldabagno": "Boiler / water heater",
  "Luce": "Light",
  "Lampada": "Lamp",
  "Televisore": "TV",
  "PC (torre)": "PC (tower)",
  "PC (monitor)": "PC (monitor)",
  "Mini PC (Home Assistant)": "Mini PC (Home Assistant)",
  "Presa smart": "Smart plug",
  "Ciabatta / multipresa": "Power strip",
  "Powerstation": "Power station",
  "Contatore della luce": "Electricity meter",
  "Gruppo di continuita'": "UPS",
  "Server": "Server",
  "NAS": "NAS",
  "Router": "Router",
  "Proxmox": "Proxmox",
  "Oggi": "Today",
  "Mese": "Month",
  "Ieri": "Yesterday",
  "Mese scorso": "Last month",
  "Mostra tutte le impostazioni (soglie, barre, ciclo in corso, colori)": "Show every setting (thresholds, bars, cycle running, colours)",
  "Entita' da cui partire": "Entity to start from",
  "Compila da solo": "Work it out for me",
  "Sensore dei kWh": "kWh sensor",
  "Sopra questi W sta lavorando": "Above these watts it is working",
  "Prezzo dei sensori che creo": "Price for the sensors I create",
  "Quanto paghi l'energia, &euro;/kWh": "What you pay for energy, &euro;/kWh",
  "Periodi da creare": "Periods to create",
  "oggi": "today",
  "settimana": "week",
  "mese": "month",
  "Crea statistiche e costi": "Create statistics and costs",
  "Cancella gli aiutanti di questa scheda": "Delete this card's helpers",
  "Mostra tutte le impostazioni": "Show every setting",
  "Proponi da solo": "Work them out for me",
  "Aggiungi una barra": "Add a bar",
  "Quante barre": "How many bars",
  "Mettile in fila da sole, la piu' accesa in cima (se la togli resta l'ordine di qui sotto)": "Line them up by themselves, the busiest on top (untick it and the order below applies)",
  "Energia &euro;/kWh": "Energy &euro;/kWh",
  "Rete e oneri &euro;/kWh": "Grid and system charges &euro;/kWh",
  "Accise &euro;/kWh": "Excise duty &euro;/kWh",
  "IVA %": "VAT %",
  "Quota fissa &euro; al giorno": "Standing charge &euro; per day",
  "Totale della bolletta": "Bill total",
  "&mdash;": "&mdash;",
  "Scrivi la tariffa": "Save the tariff",
  "Sensore dei pannelli (se ce l'hai)": "Solar panel sensor (if you have one)",
  "Prendile tutte": "Take them all",
  "Sensore della batteria (se ce l'hai)": "Battery sensor (if you have one)",
  "Crea contatori e costi": "Create meters and costs",
  "tutti": "all",
  "nessuno": "none",
  "Cancella i selezionati": "Delete the selected ones",
  "Lascia stare": "Leave them alone",
  "Nessuna barra in piu'.": "No extra bars.",
  "Come si fa, in tre mosse": "How it goes, in three moves",
  "<b>1.</b> Qui sotto scegli <b>una</b> entita' dell'apparecchio e premi <b>Compila da solo</b>: riempio io quello che trovo.<br> <b>2.</b> Guarda l'<b>anteprima a destra</b>. Quello che vedi e' quello che avrai. Se un numero dice \"&mdash;\", apri il cassetto che lo riguarda (sono qui sopra, chiusi) e scegli il sensore.<br> <b>3.</b> Se i contatori non esistono ancora, in fondo c'e' <b>Crea statistiche e costi</b>: te li creo io e poi li aggancio.<br> Il resto e' facoltativo: tasti, barre in piu', colori. Se non li tocchi, non compaiono.": "<b>1.</b> Below, pick <b>one</b> entity of the appliance and press <b>Work it out for me</b>: I fill in whatever I find.<br> <b>2.</b> Look at the <b>preview on the right</b>. What you see is what you will get. If a number reads \"&mdash;\", open the drawer it belongs to (they are above, closed) and pick the sensor.<br> <b>3.</b> If the meters do not exist yet, at the bottom there is <b>Create statistics and costs</b>: I make them and then wire them up.<br> The rest is optional: buttons, extra bars, colours. Leave them alone and they never show up.",
  "1. Capisci da solo l'apparecchio": "1. Work out the appliance by yourself",
  "Scegli <b>una qualsiasi</b> entita' dell'apparecchio - la presa, l'interruttore, lo stato - e premi il tasto. Guardo tutte le altre entita' dello <b>stesso dispositivo</b> e riempio io: i <b>watt</b>, lo <b>stato</b>, l'<b>interruttore</b> e quello <b>USB</b>, i sensori del <b>ciclo in corso</b> e il <b>disegno</b> che mi sembra giusto dal nome. Niente e' definitivo: tutto quello che trovo si cambia qui sotto, disegno compreso.": "Pick <b>any</b> entity of the appliance - the socket, the switch, the state - and press the button. I look at every other entity of the <b>same device</b> and fill in: the <b>watts</b>, the <b>state</b>, the <b>switch</b> and the <b>USB</b> one, the <b>cycle running</b> sensors and the <b>artwork</b> the name suggests. Nothing is final: everything I find can be changed below, artwork included.",
  "Due modi di contare: scegli il tuo": "Two ways of counting: pick yours",
  "Questa scheda va bene per <b>tutti e due</b> i casi, e capisce da sola quale e' il tuo da quello che compili:<br> &bull; <b>Ha dei cicli</b> (lavatrice, lavastoviglie, forno): dagli il <i>sensore dell'ultimo ciclo</i> e il riquadro fa vedere <i>fine, durata, consumo e costo</i> dell'ultimo lavaggio.<br> &bull; <b>Sta sempre acceso</b> (una presa, un PC, un frigo): lascia stare il ciclo e dagli i <i>quattro sensori dei kWh e dei costi</i> qui sopra; il riquadro diventa <b>Consumi</b> e fa vedere oggi e il mese. Le righe si spuntano qui sotto.": "This card is fine for <b>both</b> cases, and it works out which one is yours from what you fill in:<br> &bull; <b>It has cycles</b> (washing machine, dishwasher, oven): give it the <i>last-cycle sensor</i> and the box shows <i>end, duration, energy and cost</i> of the last wash.<br> &bull; <b>It is always on</b> (a socket, a PC, a fridge): leave the cycle alone and give it the <i>four kWh and cost sensors</i> above; the box becomes <b>Usage</b> and shows today and this month. The rows are ticked below.",
  "A cosa servono i tasti di accensione": "What the power buttons are for",
  "I due campi <b>Tasto ⏻</b> e <b>USB</b> qui sopra mettono un tastino tondo nella barra in alto della scheda, accanto all'ingranaggio. Premuto accende o spegne, e resta <b>verde</b> finche' l'apparecchio e' acceso. Lasciali vuoti e il tasto non compare. Va bene qualsiasi cosa si accenda: presa, luce, ventola, deumidificatore.<br> Se invece hai una <b>ciabatta</b> con tre o quattro prese, usa <b>Piu' prese</b>: diventano una fila di tastini col nome di ognuna, verdi quando danno corrente.": "The two fields <b>⏻ button</b> and <b>USB</b> above put a small round button in the card's top bar, next to the gear. Pressed, it switches on or off, and it stays <b>green</b> while the appliance is on. Leave them empty and no button shows up. Anything that switches on will do: a socket, a light, a fan, a dehumidifier.<br> If instead you have a <b>power strip</b> with three or four sockets, use <b>Several sockets</b>: they become a row of small buttons with each name, green when they are live.",
  "Nomi delle barre in piu'": "Names of the extra bars",
  "Il nome e il fondo scala (W) di ogni barra che hai scelto nel cassetto <i>Seconda barra</i>. Servono per far vedere insieme piu' misure: per esempio quanto prende dalla rete e quanto manda a casa.": "The name and the full scale (W) of every bar you picked in the <i>Second bar</i> drawer. They are for showing several measurements together: for example how much comes in from the grid and how much goes out to the house.",
  "Righe dell'«Ultimo ciclo»": "Rows of the «Last cycle» box",
  "Spunta quelle da vedere, trascinale dalla maniglia ⠿ per metterle in ordine e, se vuoi, scrivi il nome e scegli il colore che preferisci (vuoto = quelli di serie; il tasto ↺ rimette il colore originale).": "Tick the ones to show, drag them by the ⠿ handle to put them in order and, if you like, write the name and pick the colour you prefer (empty = the built-in ones; the ↺ button puts the original colour back).",
  "Crea i sensori base (se non ce li hai)": "Create the basic sensors (if you don't have them)",
  "A un apparecchio o a una presa servono <b>due aiutanti</b>: i kWh di oggi e i kWh del mese. Il <b>costo non ha un sensore</b>: sono i kWh per il prezzo, e il conto lo fa la scheda mentre lo guardi. Il prezzo lo scrivi una volta sola nella scheda <i>Energia Casa</i>, che e' la principale: qui vale la <b>sola energia</b>, se no le tasse le paghi due volte.<br> Se la presa non conta i kWh da sola ne serve un terzo, che li calcola dai Watt.": "An appliance or a socket needs <b>two helpers</b>: today's kWh and this month's kWh. The <b>cost has no sensor of its own</b>: it is the kWh times the price, and the card works it out while you look at it. You write the price once, in the <i>Energia Casa</i> card, which is the main one: here only the <b>energy alone</b> counts, otherwise you pay the taxes twice.<br> If the socket does not count kWh by itself, a third helper works them out from the watts.",
  "Qui va la <b>sola energia</b>. Rete, accise, IVA e quota fissa le conta gia' la scheda grande della casa.": "This is where the <b>energy alone</b> goes. Grid charges, excise duty, VAT and the standing charge are already counted by the big house card.",
  "Segui i <b>cicli</b>: quando finisce, quanto e' durato, quanto ha consumato (6 aiutanti e 1 automazione, una volta sola)": "Follow the <b>cycles</b>: when it ends, how long it took, how much it used (6 helpers and 1 automation, once only)",
  "Conta anche <b>quante volte parte</b> e <b>per quanto</b> (2 aiutanti per ogni periodo, piu' la soglia)": "Also count <b>how many times it starts</b> and <b>for how long</b> (2 helpers per period, plus the threshold)",
  "I sensori dei conti": "The sensors behind the numbers",
  "I quattro campi <b>kWh di oggi / euro di oggi / kWh del mese / euro del mese</b> vogliono i sensori fatti con gli aiutanti: i due <b>contatori di utenza</b> (uno a ciclo <i>giornaliero</i>, uno <i>mensile</i>) sopra al kWh dell'apparecchio, e i due sensori che moltiplicano quei kWh per il prezzo. <b>Ieri</b> e <b>mese scorso</b> non vanno messi: li legge da solo dal periodo appena chiuso degli stessi contatori.": "The four fields <b>today's kWh / today's cost / this month's kWh / this month's cost</b> want the sensors made with helpers: the two <b>utility meters</b> (one on a <i>daily</i> cycle, one <i>monthly</i>) on top of the appliance's kWh, and the two sensors that multiply those kWh by the price. <b>Yesterday</b> and <b>last month</b> are not to be filled in: the card reads them by itself from the period those same meters have just closed.",
  "I due campi <b>Tasto ⏻</b> e <b>USB</b> qui sopra mettono un tastino tondo nella barra in alto della scheda, accanto all'ingranaggio. Premuto accende o spegne, e resta <b>verde</b> finche' l'apparecchio e' acceso. Lasciali vuoti e il tasto non compare. Va bene qualsiasi cosa si accenda: presa, luce, ventola, deumidificatore.": "The two fields <b>⏻ button</b> and <b>USB</b> above put a small round button in the card's top bar, next to the gear. Pressed, it switches on or off, and it stays <b>green</b> while the appliance is on. Leave them empty and no button shows up. Anything that switches on will do: a socket, a light, a fan, a dehumidifier.",
  "Righe del riquadro «Oggi»": "Rows of the «Today» box",
  "Nomi dei circuiti": "Circuit names",
  "Le barre sotto la scheda. Se non sai quali mettere, <b>Proponi da solo</b> guarda le prese di casa e ti mette le quattro che consumano di piu' (batterie, inverter e pannelli restano fuori). Poi cambi nome e fondo scala come vuoi.": "The bars under the card. If you don't know which ones to use, <b>Work them out for me</b> looks at the sockets in the house and gives you the four that use the most (batteries, inverters and panels stay out). Then you change name and full scale as you like.",
  "Il nome e il fondo scala (W) di ogni barra.": "The name and the full scale (W) of every bar.",
  "<b>Scegli le barre da sola</b>: fa vedere le prese piu' accese del momento. Se parte il forno, il forno compare. L'elenco qui sotto non serve piu'.": "<b>Pick the bars by yourself</b>: it shows the busiest sockets of the moment. If the oven starts, the oven shows up. The list below is not needed any more.",
  "La tua tariffa": "Your tariff",
  "Questa e' la scheda <b>principale</b>: il prezzo si scrive qui, una volta sola. Gli apparecchi, le prese e le luci lo leggono da qui, non lo richiedono.<br> Scrivi le voci come stanno in bolletta: il totale lo faccio io, ed e' quello che uso per la spesa della casa. Sugli apparecchi invece vale la <b>sola energia</b>, se no le tasse le paghi due volte.": "This is the <b>main</b> card: the price is written here, once. Appliances, sockets and lights read it from here, they never ask for it again.<br> Write the items as they are on your bill: I work out the total, and that is what I use for what the house spends. On appliances, instead, only the <b>energy alone</b> counts, otherwise you pay the taxes twice.",
  "Crea i sensori base": "Create the basic sensors",
  "Il prezzo l'hai gia' scritto qui sopra: qui scegli solo <b>da quale sensore dei kWh</b> parte la casa. Creo io i contatori (ora, oggi, settimana, mese e ieri) e il costo di ogni periodo, e li aggancio alla scheda; quelli che ci sono gia' li riuso.<br> Il conto voce per voce della bolletta, i cicli degli elettrodomestici e il risparmio del fotovoltaico non si fanno da qui: stanno nella guida, in <i>esempi/luce</i>.": "You already wrote the price above: here you only pick <b>which kWh sensor</b> the house starts from. I create the meters (hour, today, week, month and yesterday) and the cost of each period, and I wire them to the card; the ones that already exist I reuse.<br> The itemised bill, the appliance cycles and the solar saving are not made from here: they are in the guide, under <i>esempi/luce</i>.",
  "Dei pannelli e della batteria faccio i kWh di oggi e del mese, e li metto nelle righe <i>Dai pannelli</i> e <i>Dalla batteria</i> (spuntale qui sopra). Va bene sia un sensore in kWh sia uno in Watt. Per la batteria scegli quello che dice <b>quanto ha dato alla casa</b> (la scarica), non la percentuale.": "Out of the panels and the battery I make today's and this month's kWh, and I put them in the <i>From the panels</i> and <i>From the battery</i> rows (tick them above). A sensor in kWh is fine, and so is one in watts. For the battery pick the one that says <b>how much it gave to the house</b> (the discharge), not the percentage.",
  "Spunta quelli da buttare. Lo storico che hanno raccolto si perde; la presa e i sensori del dispositivo non si toccano. Ci sono anche le <b>memorie dell'ultimo ciclo</b> e l'<b>automazione</b> che le riempie: se butti quelle, il riquadro dell'ultimo ciclo resta vuoto.": "Tick the ones to throw away. The history they collected is lost; the socket and the device's own sensors are never touched. There are also the <b>last-cycle memories</b> and the <b>automation</b> that fills them: throw those away and the last-cycle box stays empty.",
  "Fine del ciclo (data e ora)": "Cycle end (date and time)",
  "Durata del ciclo": "Cycle duration",
  "Consumo del ciclo (kWh)": "Cycle energy (kWh)",
  "Costo del ciclo": "Cycle cost",
  "kWh di oggi (per prese e apparecchi senza ciclo)": "Today's kWh (for sockets and appliances without cycles)",
  "Costo di oggi": "Today's cost",
  "kWh della settimana": "This week's kWh",
  "Costo della settimana": "This week's cost",
  "kWh del mese": "This month's kWh",
  "Costo del mese": "This month's cost",
  "Consumo (kWh presi dalla rete)": "Usage (kWh taken from the grid)",
  "Consumo del mese (kWh)": "This month's usage (kWh)",
  "Energia + tasse (senza pannelli)": "Energy + taxes (without the panels)",
  "Risparmio pannelli (oggi e mese)": "Panel saving (today and this month)",
  "Quello che paghi (tutto compreso)": "What you pay (everything included)",
  "Energia attuale (senza tasse)": "Energy alone (no taxes)",
  "Bolletta (il bimestre, kWh e €)": "Bill (the two months, kWh and €)",
  "kWh dai pannelli (oggi e mese)": "kWh from the panels (today and this month)",
  "kWh dalla batteria (oggi e mese)": "kWh from the battery (today and this month)",
  "Top consumo": "Top consumer",
  "Fine": "End",
  "Durata": "Duration",
  "Consumo": "Usage",
  "Costo": "Cost",
  "Costo oggi": "Cost today",
  "Settimana": "Week",
  "Costo settimana": "Cost this week",
  "Costo mese": "Cost this month",
  "Consumo mese": "Usage this month",
  "Energia + tasse": "Energy + taxes",
  "Risparmio pannelli": "Panel saving",
  "Paghi": "You pay",
  "Energia attuale": "Energy alone",
  "Mese (+ tasse)": "Month (+ taxes)",
  "Bolletta": "Bill",
  "Dai pannelli": "From the panels",
  "Dalla batteria": "From the battery",
  "Nome sulla scheda (vuoto =": "Name on the card (empty =",
  "Ultimo ciclo": "Last cycle",
  "Ciclo in corso": "Cycle running",
  "Consumi": "Usage",
  "in corso": "running",
  "ieri": "yesterday",
  "(oggi)": "(today)",
  "SPENTO": "OFF",
  "IN FUNZIONE": "RUNNING",
  "N/D": "N/A",
  "n/d": "n/a",
  "Potenza attuale": "Current power",
  "Avanzamento programma": "Programme progress",
  "AVVIO RITARDATO": "DELAYED START",
  "IN PAUSA": "PAUSED",
  "AZIONE RICHIESTA": "ACTION NEEDED",
  "TERMINATO": "FINISHED",
  "PRONTA": "READY",
  "SPENTA": "OFF",
  "ERRORE": "ERROR",
  "INTERRUZIONE": "INTERRUPTED",
  "Impostazioni": "Settings",
  "Statistiche": "Statistics",
  "Stato": "State",
  "Andamento potenza": "Power over time",
  "Andamento potenza (24h)": "Power over time (24h)",
  "Circuiti": "Circuits",
  "Il conto della luce": "The electricity bill",
  "Niente da impostare": "Nothing to set",
  "Qui compaiono i prezzi e gli interruttori che leghi alla scheda: si scelgono nel suo editor, dalla matita della plancia.": "This is where the prices and the switches you wire to the card show up: you pick them in its editor, from the dashboard's pencil.",
  "Manutenzione": "Maintenance",
  "Reset contatori": "Reset the meters",
  "Prezzo dei costi": "Price behind the costs",
  "Prezzo (€/kWh)": "Price (€/kWh)",
  "In tempo reale": "Live",
  "Programma, tempo residuo, porta: compaiono\n        solo se l'apparecchio è collegato con la sua integrazione. Misurato solo dalla presa,\n        Home Assistant ne conosce i Watt e basta.": "Programme, time left, door: they only show up if the appliance is connected through its own integration. Measured by the socket alone, Home Assistant only knows its watts.",
  "Cicli": "Cycles",
  "Tempo": "Time",
  "Consumi per periodo": "Usage by period",
  "Ultimi 7 giorni": "Last 7 days",
  "Guardo nello storico...": "Looking in the history...",
  "Nessun dato configurato": "Nothing configured",
  "Nessun dato": "No data",
  "Ancora niente: lo storico comincia adesso.": "Nothing yet: the history starts now.",
  "Lo storico non risponde.": "The history is not answering.",
  "Ultime 24 ore": "Last 24 hours",
  "Ultime 6 ore": "Last 6 hours",
  "Caricamento...": "Loading...",
  "Errore caricamento dati": "Error loading data",
  "Questo mese": "This month",
  "Quest'anno": "This year",
  "Stato apparecchio": "Appliance state",
  "Fine prevista": "Expected finish",
  "Sale": "Salt",
  "In esaurimento": "Running low",
  "Brillantante": "Rinse aid",
  "Attivo": "Active",
  "Sta lavorando": "Working",
  "sopra": "above",
  "Manca la presa che misura i Watt: si sceglie nel suo editor.": "The socket that measures the watts is missing: you pick it in the card's editor.",
  "Il conto, voce per voce &nbsp;(oggi &middot; mese)": "The bill, item by item &nbsp;(today &middot; this month)",
  "kWh presi dalla rete": "kWh taken from the grid",
  "Energia": "Energy",
  "Rete e oneri": "Grid and system charges",
  "Accise": "Excise duty",
  "Quota fissa": "Standing charge",
  "IVA": "VAT",
  "Totale": "Total",
  "Fotovoltaico": "Solar",
  "Risparmio (energia che non hai comprato)": "Saving (energy you did not buy)",
  "risparmio di oggi / del mese": "today's / this month's saving",
  "Periodo precedente": "Previous period",
  "Media settimanale": "Weekly average",
  "In evidenza": "Highlights",
  "Totale casa": "House total",
  "Non misurato": "Unmeasured",
  "Nessuno": "None",
  "Strumenti": "Tools",
  "Esegui": "Run",
  "Interruttori": "Switches",
  "Centro Notifiche": "Notification centre",
  "Mese Precedente": "Previous month",
  "Anno": "Year",
  "Anno Precedente": "Previous year",
  "Anno scorso": "Last year",
  "Questa scheda non ha aiutanti da cancellare.": "This card has no helpers to delete.",
  "Fatto:": "Done:",
  "cancellati.": "deleted.",
  "I valori me li sono segnati: se li rifai ripartono da li'.": "I wrote the values down: if you make them again they start from there.",
  "Non ce l'ho fatta:": "I could not do it:",
};
